version: "3"

services:
  db:
    image: rafanetow/node-test:latest
    environment:
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=${TYPEORM_HOST}
      -  TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=src/modules/**/*Entity.{ts,js},dist/modules/**/*Entity.{ts,js}
      - TYPEORM_MIGRATIONS=src/migrations/*.{ts,js},dist/migrations/*.js
      - TYPEORM_MIGRATIONS_DIR=src/migrations/*.{ts,js},dist/migrations/*.js
